name: Branching-create-iac
on:
   create:
jobs:
   creating_iac:
      name: 'Creating IAC for new branch'
      runs-on: ubuntu-latest
      if: ${{contains(github.ref, 'refs/heads/releases/')}}
      steps:
         - name: Set environment variables
           run: |
            # Short name for current branch. For PRs, use target branch (base ref)
            GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
            echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
         
