name: Branching-create-iac
on:
   create:
      branches:
      - 'releases/*'
      - '!main'
      - '!testes/*'
jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT
        run: echo  Woot Run on build
