name: Branching-create-iac
on:
   create
jobs:
   Run_IAC_for_new_branch:
      name: 'Running IAC for new Branch'
      runs-on: ubuntu-latest
      if: ${{contains(github.ref, 'refs/heads/releases/')}}
      steps:
         - name: Setting Branch Name to Variable
           run: |
            # Short name for current branch. For PRs, use target branch (base ref)
            echo "BRANCH_NAME=$(echo $GITHUB_REF | cut -d'/' -f 4)" >> $GITHUB_ENV
         
         - name: 'Setting IAC for new branch'
           run: |
            echo ${{ env.BRANCH_NAME }}
         - uses: azure/login@v1
           with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}
              enable-AzPSSession: true

         - name: Install ADE extension
           uses: azure/powershell@v1
           with:
             azPSVersion: "3.1.0"
             inlineScript: |
               az extension add --name devcenter --upgrade
               
         - name: Register DevCenter
           uses: azure/powershell@v1
           with:
             azPSVersion: "3.1.0"
             inlineScript: |
               az provider register --namespace Microsoft.DevCenter


         - name: Create DLZ Project
           uses: azure/powershell@v1
           with:
             azPSVersion: "3.1.0"
             inlineScript: |
               az devcenter admin project create --name 'newproject-${{ env.BRANCH_NAME }}-dev' --resource-group 'rg-developer_landing_zone' --location 'westus3' --dev-center-id ${{ secrets.DEVCENTERID }}
         
         - name: Create DLZ Project Environment Types
           uses: azure/powershell@v1
           with:
             azPSVersion: "3.1.0"
             inlineScript: |

      
         
