name: Branching-create-iac
on:
   create:
jobs:
   creating_iac:
      name: 'Creating IAC for new branch'
      runs-on: ubuntu-latest
      if: ${{contains(github.ref, 'refs/heads/releases/')}}
      steps:
         - name: Print the input tag to STDOUT
           run: echo  Woot Run on build
