name: Podcast Web CICD

on:
  push:
    branches: [main]
    paths:
      - "src/Web/**"
      - ".github/workflows/podcast-web.yml"
      - "deploy/Web/web.bicep"
  pull_request:
    branches: [main]
    paths:
      - "src/Web/**"
      - ".github/workflows/podcast-web.yml"
      - "deploy/Web/web.bicep"
  workflow_dispatch:

jobs:
  buildDeployStaging:
    name: "Build and deploy to Staging environment"
    if: "!contains(github.ref, 'refs/heads/main')"
    uses: ./.github/workflows/template-web.yml
    concurrency:
      group: staging-web
      cancel-in-progress: true
    secrets: inherit
    with:
      environment: staging

  buildDeployProd:
    name: "Build and deploy main branch to Production environment"
    if: contains(github.ref, 'refs/heads/main')
    uses: ./.github/workflows/template-web.yml
    concurrency:
      group: prod-web
      cancel-in-progress: true
    secrets: inherit
    with:
      environment: prod

