# This is a basic workflow to help you get started with Actions

name: Podcast Load Test

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  loadTest:
    name: Load Test

    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Actions 
        uses: actions/checkout@v3
          
      - name: Login to Azure
        uses: azure/login@v1
        continue-on-error: false
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Create Resource Group
        uses: azure/powershell@v1
        continue-on-error: false
        with:
          inlineScript: |
            az group create --name "rg-podcast" --location "eastus"
          azPSVersion: "latest"      
          
      - name: Create Azure Load Testing resource
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
          template: ./Test/ARMTemplate/template.json
          parameters: ./Test/ARMTemplate/parameters.json name="lt-podcast" location="eastus"
        
      - name: 'Azure Load Testing'
        uses: azure/load-testing@v1
        with:
          loadTestConfigFile: 'Test/config.yml'
          loadTestResource: 'lt-podcast'
          resourceGroup: 'rg-podcast'
          env: |
              [
                {
                "name": "webapp",
                "value": "as-podcast-hub.azurewebsites.net"
                }
              ]

    # publish artifacts  
      - uses: actions/upload-artifact@v2
        with:
          name: loadTestResults
          path: ${{ github.workspace }}/loadTest
